# Makefile for the Python full-stack template backend.
# Uses uv for environment and dependency management.

.DEFAULT_GOAL := help
SHELL := bash

UV ?= uv
APP ?= src.main:app
HOST ?= 0.0.0.0
PORT ?= 8000

.PHONY: help
help: ## Show this help message
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) \
		| sort \
		| awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-20s\033[0m %s\n", $$1, $$2}'

.PHONY: install
install: ## Create the virtualenv and install all dependencies (dev included)
	$(UV) sync --extra dev
	$(UV) run pre-commit install

.PHONY: lock
lock: ## Refresh the uv lockfile
	$(UV) lock

.PHONY: format
format: ## Auto-format code with Ruff and config files with prettier
	$(UV) run ruff format src tests
	$(UV) run ruff check --fix src tests
	npx --yes prettier --write "**/*.{yml,yaml,json,md}"

.PHONY: lint
lint: ## Run Ruff, prettier check, and mypy
	$(UV) run ruff check src tests
	$(UV) run ruff format --check src tests
	npx --yes prettier --check "**/*.{yml,yaml,json,md}"
	$(UV) run mypy src

.PHONY: typecheck
typecheck: ## Run the mypy static type checker
	$(UV) run mypy src

.PHONY: test
test: ## Run the test suite with coverage
	$(UV) run pytest

.PHONY: test-cov
test-cov: ## Run tests and emit an HTML + XML coverage report
	$(UV) run coverage erase
	$(UV) run pytest --cov-report=xml --cov-report=html
	$(UV) run coverage combine || true
	$(UV) run coverage report

.PHONY: check
check: lint test ## Run linters, type checks and tests

.PHONY: run
run: ## Run the FastAPI dev server with hot reload
	$(UV) run uvicorn $(APP) --host $(HOST) --port $(PORT) --reload

.PHONY: worker
worker: ## Run the Celery worker
	$(UV) run celery -A src.worker worker --loglevel=info

.PHONY: beat
beat: ## Run the Celery beat scheduler
	$(UV) run celery -A src.worker beat --loglevel=info

.PHONY: migrate
migrate: ## Apply database migrations to the latest revision
	$(UV) run alembic upgrade head

.PHONY: migration
migration: ## Create a new autogenerated migration: make migration m="message"
	$(UV) run alembic revision --autogenerate -m "$(m)"

.PHONY: downgrade
downgrade: ## Downgrade the database by one revision
	$(UV) run alembic downgrade -1

.PHONY: schema
schema: ## Regenerate the database schema diagram with Paracelsus
	$(UV) run paracelsus graph src.models:Base --import-module "src.auth.models" --import-module "src.posts.models" > docs/dev/schema.mermaid

.PHONY: pre-commit
pre-commit: ## Run all pre-commit hooks against every file
	$(UV) run pre-commit run --all-files

.PHONY: build
build: ## Build the sdist and wheel distributions
	$(UV) build

.PHONY: publish
publish: build ## Build and publish the package to PyPI
	$(UV) publish

.PHONY: docker-build
docker-build: ## Build the production Docker image
	docker build -f docker/Dockerfile -t app:latest .

.PHONY: docker-up
docker-up: ## Start the full development stack with Docker Compose
	docker compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml up --build

.PHONY: docker-down
docker-down: ## Stop and remove the Docker Compose stack
	docker compose -f docker/docker-compose.yml -f docker/docker-compose.dev.yml down

.PHONY: clean
clean: ## Remove caches, build artifacts and coverage data
	rm -rf build dist *.egg-info .pytest_cache .ruff_cache .mypy_cache htmlcov
	find . -type d -name __pycache__ -exec rm -rf {} + 2>/dev/null || true
	rm -f .coverage .coverage.*
